### ISSUE TITLE
__STDC__ feature macro is non-exhaustive

### ISSUE THREAD

**Issue by sykhro** [simonfxr/cxx-header-utils#1]
Ran into this while compiling `fiber` under MSVC.
`<hu/lang.h>` uses `__STDC__` to detect C-mode, but this macro is not defined if the C standard version chosen is >= 11 (at least, on MSVC). I replaced it with `__STDC_VERSION__` as a workaround since I don't need C < 11 anyway, not sure what a suitable crossplatform solution would be.

**Comment by simonfxr** [comment]
@sykhro Thx for reporting, it should be fixed. Please let me know if it works for you

**Comment by sykhro** [comment]
Yup, that does the trick. Thanks!

**Comment by sykhro** [comment]
(side note: I'm using this through `fiber` so this submodule would need to be updated there)

**Comment by simonfxr** [comment]
Okay, I updated it
